port: 6666

path: /static/app.js

admin:
  client_id: admin
  client_secret: secret_admin
  pair_key: pair_admin

clients:
  - client_id: id_04aba01
    client_secret: 29f4e3d3a4302b4d9e01
    pair_key: pair_3fd01
  - client_id: id_04aba02
    client_secret: 29f4e3d3a4302b4d9e02
    pair_key: pair_3fd02
  - client_id: aaa
    client_secret: bbb
    pair_key: ccc

