relay: wss://example.com/ws

auth: client_id:client_secret

actions:
  action1:
    target: client_name:pk
    bind: tcp:0.0.0.0:17890:192.168.1.2:17890
  action2:
    target: client_name:pk
    socks5: 0.0.0.0:17890
