package protocol

const (
	VERSION = 1
)

const (
	COMMAND_AUTHENTICATE = 0x01
	COMMAND_HANDSHAKE    = 0x02
	COMMAND_TRANSMISSION = 0x03
	COMMAND_CONNECT      = 0x04
	COMMAND_BIND         = 0x05
	COMMAND_CLOSE        = 0xff
)
